--DECLARE @CART_ID1 VARCHAR(50)
SET @CART_ID1  = SELECT RANDOM_UUID() FROM DUAL;
SET @CART_ID2  = SELECT RANDOM_UUID() FROM DUAL;
SET @CART_ID3 =  SELECT RANDOM_UUID() FROM DUAL;
insert into SHOPPING_CART (CART_ID, CUSTOMER_ID) VALUES (@CART_ID1, 1);
insert into SHOPPING_CART (CART_ID, CUSTOMER_ID) VALUES (@CART_ID2, 2);
insert into SHOPPING_CART (CART_ID, CUSTOMER_ID) VALUES (@CART_ID3, 3);

INSERT INTO CART_ITEM(ID, QTY, SKU, UNIT_COST, CART_ID) VALUES( RANDOM_UUID(), 11, 'SKU1', 10l, @CART_ID1);


INSERT INTO CART_ITEM(ID, QTY, SKU, UNIT_COST, CART_ID) VALUES( RANDOM_UUID(), 21, 'SKU1', 10l, @CART_ID2);
INSERT INTO CART_ITEM(ID, QTY, SKU, UNIT_COST, CART_ID) VALUES( RANDOM_UUID(), 22, 'SKU1', 20l, @CART_ID2);

INSERT INTO CART_ITEM(ID, QTY, SKU, UNIT_COST, CART_ID) VALUES(RANDOM_UUID(), 31, 'SKU1', 10l, @CART_ID3);
INSERT INTO CART_ITEM(ID, QTY, SKU, UNIT_COST, CART_ID) VALUES(RANDOM_UUID(), 32, 'SKU1', 20l, @CART_ID3);
INSERT INTO CART_ITEM(ID, QTY, SKU, UNIT_COST, CART_ID) VALUES(RANDOM_UUID(), 33, 'SKU1', 30l, @CART_ID3);
